<?php
/**
 * Handoff Block Categories
 *
 * This file is auto-generated by the Handoff WordPress compiler.
 * Do not edit this file directly - changes will be overwritten.
 *
 * @package Handoff_Blocks
 */

if (!defined('ABSPATH')) {
  exit(); // Exit if accessed directly
}

/**
 * Get the list of Handoff block categories
 *
 * @return array Array of category definitions
 */
function handoff_get_block_categories() {
  return [
    // Default fallback category
    [
      'slug' => 'handoff',
      'title' => __('Handoff Blocks', 'handoff'),
      'icon' => 'admin-customizer',
    ],
    [
      'slug' => 'handoff-hero',
      'title' => __('Hero', 'handoff'),
      'icon' => 'admin-customizer',
    ],
  ];
}
