/**
 * Generates block.json for a Gutenberg block
 */

import { HandoffComponent, HandoffProperty, BlockJsonOutput, GutenbergAttribute } from '../types';
import { sanitizeReservedName } from './handlebars-to-jsx/utils';

/**
 * Convert a group name to a category slug
 * @param group - The group name from the component API
 * @returns The category slug (kebab-case, prefixed with 'handoff-')
 */
const groupToCategory = (group: string | undefined): string => {
  if (!group) {
    return 'handoff';
  }
  // Convert to kebab-case and prefix with 'handoff-'
  const slug = group
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return `handoff-${slug}`;
};

/**
 * Convert a group name to a display title
 * @param group - The group name from the component API
 * @returns The formatted title for display
 */
const groupToTitle = (group: string): string => {
  // Capitalize first letter of each word
  return group
    .split(/[\s_-]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
};

/**
 * Generate the categories PHP file content
 * @param components - Array of all components to extract unique groups from
 * @returns PHP file content defining the categories
 */
const generateCategoriesPhp = (components: HandoffComponent[]): string => {
  // Collect unique groups
  const groups = new Set<string>();
  for (const component of components) {
    if (component.group) {
      groups.add(component.group);
    }
  }
  
  // Sort groups alphabetically
  const sortedGroups = Array.from(groups).sort();
  
  // Generate the category array entries
  const categoryEntries = sortedGroups.map(group => {
    const slug = groupToCategory(group);
    const title = groupToTitle(group);
    return `    [
      'slug'  => '${slug}',
      'title' => __('${title}', 'handoff'),
      'icon'  => 'admin-customizer',
    ],`;
  }).join('\n');
  
  return `<?php
/**
 * Handoff Block Categories
 * 
 * This file is auto-generated by the Handoff WordPress compiler.
 * Do not edit this file directly - changes will be overwritten.
 * 
 * @package Handoff_Blocks
 */

if (!defined('ABSPATH')) {
  exit; // Exit if accessed directly
}

/**
 * Get the list of Handoff block categories
 * 
 * @return array Array of category definitions
 */
function handoff_get_block_categories() {
  return [
    // Default fallback category
    [
      'slug'  => 'handoff',
      'title' => __('Handoff Blocks', 'handoff'),
      'icon'  => 'admin-customizer',
    ],
${categoryEntries}
  ];
}
`;
};

/**
 * Get default value for a type
 */
const getDefaultForType = (type: string): any => {
  switch (type) {
    case 'text':
    case 'richtext':
    case 'select':
      return '';
    case 'number':
      return 0;
    case 'boolean':
      return false;
    case 'image':
      return { src: '', alt: '' };
    case 'link':
      return { label: '', url: '', opensInNewTab: false };
    case 'button':
      return { label: '', href: '#', target: '', rel: '', disabled: false };
    case 'object':
      return {};
    case 'array':
      return [];
    default:
      return '';
  }
};

/**
 * Maps Handoff property types to Gutenberg attribute types
 * @param property - The property definition
 * @param previewValue - Optional value from generic preview to use as default if property.default is not set
 */
const mapPropertyType = (property: HandoffProperty, previewValue?: any): GutenbergAttribute => {
  // Use property.default first, then preview value, then type-specific fallback
  const getDefault = (typeDefault: any) => {
    if (property.default !== undefined) return property.default;
    if (previewValue !== undefined) return previewValue;
    return typeDefault;
  };

  switch (property.type) {
    case 'text':
    case 'richtext':
      return { type: 'string', default: getDefault('') };
    
    case 'number':
      return { type: 'number', default: getDefault(0) };
    
    case 'boolean':
      return { type: 'boolean', default: getDefault(false) };
    
    case 'image':
      return { 
        type: 'object', 
        default: getDefault({ src: '', alt: '' })
      };
    
    case 'link':
      return { 
        type: 'object', 
        default: getDefault({ label: '', url: '', opensInNewTab: false })
      };
    
    case 'button':
      return { 
        type: 'object', 
        default: getDefault({ label: '', href: '#', target: '', rel: '', disabled: false })
      };
    
    case 'object':
      // For objects, create default from nested properties or use preview value
      const objectDefault: Record<string, any> = {};
      if (property.properties) {
        const previewObj = typeof previewValue === 'object' ? previewValue : {};
        for (const [key, nestedProp] of Object.entries(property.properties)) {
          objectDefault[key] = nestedProp.default ?? previewObj?.[key] ?? getDefaultForType(nestedProp.type);
        }
      }
      return { 
        type: 'object', 
        default: getDefault(objectDefault)
      };
    
    case 'array':
      // For arrays, only include the first item in default (full defaults go in example.attributes)
      // This prevents issues with the 10up Repeater not assigning IDs to initial items
      // Check property.default first, then preview value
      const arraySource = property.default !== undefined 
        ? property.default 
        : (Array.isArray(previewValue) ? previewValue : []);
      const fullArray = Array.isArray(arraySource) ? arraySource : [];
      const singleItemDefault = fullArray.length > 0 ? [fullArray[0]] : [];
      return { 
        type: 'array', 
        default: singleItemDefault
      };
    
    case 'select':
      return { 
        type: 'string', 
        default: getDefault(property.options?.[0]?.value || '')
      };
    
    default:
      return { type: 'string', default: getDefault('') };
  }
};

/**
 * Choose an appropriate icon based on component type/group
 */
const chooseIcon = (component: HandoffComponent): string => {
  const group = component.group?.toLowerCase() || '';
  const id = component.id.toLowerCase();
  
  if (group.includes('hero') || id.includes('hero')) {
    return 'format-image';
  }
  if (group.includes('card') || id.includes('card')) {
    return 'index-card';
  }
  if (group.includes('form') || id.includes('form')) {
    return 'feedback';
  }
  if (group.includes('nav') || id.includes('nav')) {
    return 'menu';
  }
  if (group.includes('footer') || id.includes('footer')) {
    return 'table-row-after';
  }
  if (group.includes('header') || id.includes('header')) {
    return 'table-row-before';
  }
  
  return 'admin-customizer';
};

/**
 * Convert component ID to block name (kebab-case)
 * Also sanitizes reserved JavaScript words by prefixing with 'block-'
 */
const toBlockName = (id: string): string => {
  const kebabCase = id.toLowerCase().replace(/_/g, '-');
  // Check if the base name (without underscores/hyphens) is a reserved word
  const baseName = kebabCase.replace(/-/g, '');
  const sanitized = sanitizeReservedName(baseName);
  // If it was sanitized, convert the sanitized name to kebab-case
  if (sanitized !== baseName) {
    return sanitized.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  }
  return kebabCase;
};

/**
 * Generate block.json content
 * @param component - The Handoff component data
 * @param hasScreenshot - Whether a screenshot image is available for this block
 */
const generateBlockJson = (component: HandoffComponent, hasScreenshot: boolean = false): string => {
  const blockName = toBlockName(component.id);
  
  // Get generic preview values to use as defaults when property.default is not set
  const genericPreviewValues = component.previews?.generic?.values || {};
  
  // Convert properties to Gutenberg attributes
  const attributes: Record<string, GutenbergAttribute> = {};
  
  for (const [key, property] of Object.entries(component.properties)) {
    // Convert snake_case to camelCase for attribute names
    const attrName = key.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
    // Pass preview value for this property to use as fallback default
    const previewValue = genericPreviewValues[key];
    attributes[attrName] = mapPropertyType(property, previewValue);
  }
  
  // Add overlay opacity if we detect a hero/subheader component
  if (component.code.includes('overlay') && !attributes.overlayOpacity) {
    attributes.overlayOpacity = { type: 'number', default: 0.6 };
  }
  
  // Add align attribute with default of 'full' for full-width blocks
  attributes.align = { type: 'string', default: 'full' };
  
  const blockJson: BlockJsonOutput = {
    $schema: 'https://schemas.wp.org/trunk/block.json',
    apiVersion: 3,
    name: `handoff/${blockName}`,
    version: '1.0.0',
    title: component.title,
    category: groupToCategory(component.group),
    icon: chooseIcon(component),
    description: component.description.replace(/\n\s+/g, ' ').trim(),
    keywords: component.tags || [],
    textdomain: 'handoff',
    editorScript: 'file:./index.js',
    editorStyle: 'file:./index.css',
    style: 'file:./style-index.css',
    render: 'file:./render.php',
    attributes,
    supports: {
      align: ['none', 'wide', 'full'],
      html: false
    }
  };
  
  // Build example attributes from the full preview values
  // This provides realistic sample data for the block preview
  const exampleAttributes: Record<string, any> = {};
  for (const [key, property] of Object.entries(component.properties)) {
    const attrName = key.replace(/_([a-z])/g, (_, letter) => letter.toUpperCase());
    const previewValue = genericPreviewValues[key];
    if (previewValue !== undefined) {
      exampleAttributes[attrName] = previewValue;
    }
  }
  
  // Add example with preview image if screenshot is available, or with full preview data
  if (hasScreenshot || Object.keys(exampleAttributes).length > 0) {
    blockJson.example = {
      viewportWidth: 1200,
      attributes: exampleAttributes
    };
  }
  
  return JSON.stringify(blockJson, null, 2);
};

export { generateBlockJson, toBlockName, mapPropertyType, generateCategoriesPhp, groupToCategory };
