/**
 * Generates block.json for a Gutenberg block
 */

import { HandoffComponent, HandoffProperty, BlockJsonOutput, GutenbergAttribute, HandoffMetadata, DynamicArrayConfig, BreadcrumbsArrayConfig, TaxonomyArrayConfig, PaginationArrayConfig, isBreadcrumbsConfig, isTaxonomyConfig, isPaginationConfig } from '../types';
import { sanitizeReservedName, normalizeSelectOptions, toCamelCase, getTemplateReferencedAttributeNames } from './handlebars-to-jsx/utils';

/**
 * Convert a group name to a category slug
 * @param group - The group name from the component API
 * @returns The category slug (kebab-case, prefixed with 'handoff-')
 */
const groupToCategory = (group: string | undefined): string => {
  if (!group) {
    return 'handoff';
  }
  // Convert to kebab-case and prefix with 'handoff-'
  const slug = group
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return `handoff-${slug}`;
};

/**
 * Convert a group name to a display title
 * @param group - The group name from the component API
 * @returns The formatted title for display
 */
const groupToTitle = (group: string): string => {
  // Capitalize first letter of each word
  return group
    .split(/[\s_-]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
};

/**
 * Generate the categories PHP file content
 * @param components - Array of all components to extract unique groups from
 * @returns PHP file content defining the categories
 */
const generateCategoriesPhp = (components: HandoffComponent[]): string => {
  // Collect unique groups
  const groups = new Set<string>();
  for (const component of components) {
    if (component.group) {
      groups.add(component.group);
    }
  }
  
  // Sort groups alphabetically
  const sortedGroups = Array.from(groups).sort();
  
  // Generate the category array entries
  const categoryEntries = sortedGroups.map(group => {
    const slug = groupToCategory(group);
    const title = groupToTitle(group);
    return `    [
      'slug'  => '${slug}',
      'title' => __('${title}', 'handoff'),
      'icon'  => 'admin-customizer',
    ],`;
  }).join('\n');
  
  return `<?php
/**
 * Handoff Block Categories
 * 
 * This file is auto-generated by the Handoff WordPress compiler.
 * Do not edit this file directly - changes will be overwritten.
 * 
 * @package Handoff_Blocks
 */

if (!defined('ABSPATH')) {
  exit; // Exit if accessed directly
}

/**
 * Get the list of Handoff block categories
 * 
 * @return array Array of category definitions
 */
function handoff_get_block_categories() {
  return [
    // Default fallback category
    [
      'slug'  => 'handoff',
      'title' => __('Handoff Blocks', 'handoff'),
      'icon'  => 'admin-customizer',
    ],
${categoryEntries}
  ];
}
`;
};

/**
 * Get default value for a type
 */
const getDefaultForType = (type: string): any => {
  switch (type) {
    case 'text':
    case 'richtext':
    case 'select':
      return '';
    case 'number':
      return 0;
    case 'boolean':
      return false;
    case 'image':
      return { src: '', alt: '' };
    case 'link':
      return { label: '', url: '', opensInNewTab: false };
    case 'button':
      return { label: '', href: '#', target: '', rel: '', disabled: false };
    case 'object':
      return {};
    case 'array':
      return [];
    default:
      return '';
  }
};

/**
 * Maps Handoff property types to Gutenberg attribute types
 * @param property - The property definition
 * @param previewValue - Optional value from generic preview to use as default if property.default is not set
 */
const mapPropertyType = (property: HandoffProperty, previewValue?: any): GutenbergAttribute => {
  // Use property.default first, then preview value, then type-specific fallback
  const getDefault = (typeDefault: any) => {
    if (property.default !== undefined) return property.default;
    if (previewValue !== undefined) return previewValue;
    return typeDefault;
  };

  switch (property.type) {
    case 'richtext':
      // richtext uses InnerBlocks – content is stored in post content, not as an attribute
      return null as any;

    case 'pagination':
      // pagination items are auto-generated from WP_Query results, not stored as an attribute
      return null as any;

    case 'text':
      return { type: 'string', default: getDefault('') };
    
    case 'number':
      return { type: 'number', default: getDefault(0) };
    
    case 'boolean':
      return { type: 'boolean', default: getDefault(false) };
    
    case 'image':
      return { 
        type: 'object', 
        default: getDefault({ src: '', alt: '' })
      };
    
    case 'link':
      return { 
        type: 'object', 
        default: getDefault({ label: '', url: '', opensInNewTab: false })
      };
    
    case 'button':
      return { 
        type: 'object', 
        default: getDefault({ label: '', href: '#', target: '', rel: '', disabled: false })
      };
    
    case 'object':
      // For objects, create default from nested properties or use preview value
      const objectDefault: Record<string, any> = {};
      if (property.properties) {
        const previewObj = typeof previewValue === 'object' ? previewValue : {};
        for (const [key, nestedProp] of Object.entries(property.properties)) {
          objectDefault[key] = nestedProp.default ?? previewObj?.[key] ?? getDefaultForType(nestedProp.type);
        }
      }
      return { 
        type: 'object', 
        default: getDefault(objectDefault)
      };
    
    case 'array':
      // For arrays, only include the first item in default (full defaults go in example.attributes)
      // This prevents issues with the 10up Repeater not assigning IDs to initial items
      // Check property.default first, then preview value
      const arraySource = property.default !== undefined 
        ? property.default 
        : (Array.isArray(previewValue) ? previewValue : []);
      const fullArray = Array.isArray(arraySource) ? arraySource : [];
      const singleItemDefault = fullArray.length > 0 ? [fullArray[0]] : [];
      return { 
        type: 'array', 
        default: singleItemDefault
      };
    
    case 'select': {
      const opts = normalizeSelectOptions(property.options);
      return {
        type: 'string',
        default: getDefault(opts[0]?.value ?? '')
      };
    }
    
    default:
      return { type: 'string', default: getDefault('') };
  }
};

/**
 * Choose an appropriate icon based on component type/group
 */
const chooseIcon = (component: HandoffComponent): string => {
  const group = component.group?.toLowerCase() || '';
  const id = component.id.toLowerCase();
  
  if (group.includes('hero') || id.includes('hero')) {
    return 'format-image';
  }
  if (group.includes('card') || id.includes('card')) {
    return 'index-card';
  }
  if (group.includes('form') || id.includes('form')) {
    return 'feedback';
  }
  if (group.includes('nav') || id.includes('nav')) {
    return 'menu';
  }
  if (group.includes('footer') || id.includes('footer')) {
    return 'table-row-after';
  }
  if (group.includes('header') || id.includes('header')) {
    return 'table-row-before';
  }
  
  return 'admin-customizer';
};

/**
 * Convert component ID to block name (kebab-case)
 * Also sanitizes reserved JavaScript words by prefixing with 'block-'
 */
const toBlockName = (id: string): string => {
  const kebabCase = id.toLowerCase().replace(/_/g, '-');
  // Check if the base name (without underscores/hyphens) is a reserved word
  const baseName = kebabCase.replace(/-/g, '');
  const sanitized = sanitizeReservedName(baseName);
  // If it was sanitized, convert the sanitized name to kebab-case
  if (sanitized !== baseName) {
    return sanitized.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  }
  return kebabCase;
};

/**
 * Generate block.json content
 * @param component - The Handoff component data
 * @param hasScreenshot - Whether a screenshot image is available for this block
 * @param apiUrl - Optional base API URL to construct Handoff component page URL
 * @param dynamicArrayConfigs - Optional dynamic array configurations keyed by field name
 */
const generateBlockJson = (
  component: HandoffComponent, 
  hasScreenshot: boolean = false, 
  apiUrl?: string,
  dynamicArrayConfigs?: Record<string, DynamicArrayConfig | BreadcrumbsArrayConfig | TaxonomyArrayConfig | PaginationArrayConfig>,
  innerBlocksField?: string | null
): string => {
  const blockName = toBlockName(component.id);
  
  // Get generic preview values to use as defaults when property.default is not set
  const genericPreviewValues = component.previews?.generic?.values || {};
  
  // Convert properties to Gutenberg attributes
  const attributes: Record<string, GutenbergAttribute> = {};
  
  for (const [key, property] of Object.entries(component.properties)) {
    // Use toCamelCase so attribute names match index-js and avoid globals (e.g. body -> blockBody)
    const attrName = toCamelCase(key);
    // Pass preview value for this property to use as fallback default
    const previewValue = genericPreviewValues[key];
    const mapped = mapPropertyType(property, previewValue);

    // Only the innerBlocksField richtext returns null (content stored via InnerBlocks);
    // other richtext fields are string attributes.
    if (mapped === null && property.type === 'richtext' && key !== innerBlocksField) {
      attributes[attrName] = { type: 'string', default: previewValue ?? '' };
      continue;
    }
    if (mapped === null) continue;
    attributes[attrName] = mapped;
    
    // Add dynamic array control attributes if this field has a dynamic config
    const dynamicConfig = dynamicArrayConfigs?.[key];
    if (property.type === 'array' && dynamicConfig) {
      if (isBreadcrumbsConfig(dynamicConfig)) {
        // Breadcrumbs are server-rendered — override array default to [] so preview
        // never shows Handoff preview values as editable RichText items.
        attributes[attrName] = { type: 'array', default: [] };
        attributes[`${attrName}Enabled`] = { type: 'boolean', default: true };
      } else if (isTaxonomyConfig(dynamicConfig)) {
        // Taxonomy terms are server-rendered — same override to prevent editable items.
        attributes[attrName] = { type: 'array', default: [] };
        // Enabled toggle + selected taxonomy + source (auto vs manual)
        attributes[`${attrName}Enabled`] = { type: 'boolean', default: false };
        attributes[`${attrName}Taxonomy`] = {
          type: 'string',
          default: dynamicConfig.taxonomies[0] || 'post_tag'
        };
        attributes[`${attrName}Source`] = { type: 'string', default: 'auto' };
      } else if (isPaginationConfig(dynamicConfig)) {
        // Pagination is server-rendered — override array default to [].
        attributes[attrName] = { type: 'array', default: [] };
        attributes[`${attrName}Enabled`] = { type: 'boolean', default: true };
      } else {
        // Posts (DynamicArrayConfig): full attribute set
        // Source: 'query' (query builder), 'select' (hand-pick posts), or 'manual' (static repeater)
        const sourceDefault = dynamicConfig.selectionMode === 'manual' ? 'select' : 'query';
        attributes[`${attrName}Source`] = { 
          type: 'string', 
          default: sourceDefault,
          enum: ['query', 'select', 'manual']
        };
        // Selected post type for query mode
        attributes[`${attrName}PostType`] = { 
          type: 'string', 
          default: dynamicConfig.defaultPostType || dynamicConfig.postTypes[0] || 'post' 
        };
        // Selected posts array: [{id: number, type: string}]
        attributes[`${attrName}SelectedPosts`] = { 
          type: 'array', 
          default: [] 
        };
        // Query arguments for query builder mode
        const defaultQueryArgs = {
          post_type: dynamicConfig.defaultPostType || dynamicConfig.postTypes[0] || 'post',
          posts_per_page: dynamicConfig.maxItems || 6,
          orderby: 'date',
          order: 'DESC',
          tax_query: [],
          ...(dynamicConfig.defaultQueryArgs || {})
        };
        attributes[`${attrName}QueryArgs`] = { 
          type: 'object', 
          default: defaultQueryArgs
        };
        // Field mapping configuration
        attributes[`${attrName}FieldMapping`] = {
          type: 'object',
          default: dynamicConfig.fieldMapping || {}
        };
        // Item overrides (apply to all items in query mode, e.g. card type)
        attributes[`${attrName}ItemOverrides`] = {
          type: 'object',
          default: {}
        };
        // Render mode: 'mapped' or 'template'
        attributes[`${attrName}RenderMode`] = {
          type: 'string',
          default: dynamicConfig.renderMode || 'mapped'
        };
        // Template path for template mode
        if (dynamicConfig.templatePath) {
          attributes[`${attrName}TemplatePath`] = {
            type: 'string',
            default: dynamicConfig.templatePath
          };
        }
        // Pagination toggle (auto-detected from component's pagination sub-property)
        if (dynamicConfig.pagination) {
          attributes[`${attrName}PaginationEnabled`] = {
            type: 'boolean',
            default: true
          };
        }
      }
    }
  }

  // Build a reverse lookup: camelCase attr name → property type, so we can skip excluded types below
  const propTypeByAttr: Record<string, string> = {};
  for (const [key, prop] of Object.entries(component.properties)) {
    propTypeByAttr[toCamelCase(key)] = prop.type;
  }

  // Ensure any property referenced in the template has an attribute (API may omit from properties).
  // Skip properties whose type is excluded from block attributes (pagination, richtext used as InnerBlocks).
  const EXCLUDED_TYPES = new Set(['pagination']);
  for (const attrName of getTemplateReferencedAttributeNames(component.code)) {
    if (attrName in attributes) continue;
    const propType = propTypeByAttr[attrName];
    if (propType && EXCLUDED_TYPES.has(propType)) continue;
    attributes[attrName] = { type: 'string', default: '' };
  }
  
  // Add overlay opacity if we detect a hero/subheader component
  if (component.code.includes('overlay') && !attributes.overlayOpacity) {
    attributes.overlayOpacity = { type: 'number', default: 0.6 };
  }
  
  // Add align attribute with default of 'full' for full-width blocks
  attributes.align = { type: 'string', default: 'full' };
  
  const blockJson: BlockJsonOutput = {
    $schema: 'https://schemas.wp.org/trunk/block.json',
    apiVersion: 3,
    name: `handoff/${blockName}`,
    version: '1.0.0',
    title: component.title,
    category: groupToCategory(component.group),
    icon: chooseIcon(component),
    description: component.description.replace(/\n\s+/g, ' ').trim(),
    keywords: component.tags || [],
    textdomain: 'handoff',
    editorScript: 'file:./index.js',
    editorStyle: 'file:./index.css',
    style: 'file:./style-index.css',
    render: 'file:./render.php',
    attributes,
    supports: {
      align: ['none', 'wide', 'full'],
      html: false
    }
  };
  
  // Build example attributes from the full preview values
  // This provides realistic sample data for the block preview
  const exampleAttributes: Record<string, any> = {};
  for (const [key, property] of Object.entries(component.properties)) {
    const attrName = toCamelCase(key);
    const previewValue = genericPreviewValues[key];
    if (previewValue !== undefined) {
      exampleAttributes[attrName] = previewValue;
    }
  }
  
  // Add example with preview image if screenshot is available, or with full preview data
  if (hasScreenshot || Object.keys(exampleAttributes).length > 0) {
    blockJson.example = {
      viewportWidth: 1200,
      attributes: exampleAttributes
    };
  }
  
  // Add Handoff metadata for linking to design system
  const handoffMetadata: HandoffMetadata = {};
  
  // Construct Handoff component page URL from API URL
  if (apiUrl) {
    // Remove /api suffix if present and construct component page URL
    const baseUrl = apiUrl.replace(/\/api\/?$/, '');
    handoffMetadata.handoffUrl = `${baseUrl}/system/component/${component.id}`;
  } else if (component.preview) {
    // Fall back to component's preview URL if available
    handoffMetadata.handoffUrl = component.preview;
  }
  
  // Add Figma URL if available
  if (component.figma) {
    handoffMetadata.figmaUrl = component.figma;
  }
  
  // Only add __handoff if we have at least one URL
  if (handoffMetadata.handoffUrl || handoffMetadata.figmaUrl) {
    blockJson.__handoff = handoffMetadata;
  }
  
  return JSON.stringify(blockJson, null, 2);
};

export { generateBlockJson, toBlockName, mapPropertyType, generateCategoriesPhp, groupToCategory };
