/**
 * Generate shared React components for the blocks plugin.
 * These are generated once and shared across all blocks.
 *
 * @package Handoff_Blocks
 */

/**
 * Generate the PostSelector component code
 */
export const generatePostSelector = (): string => {
  return `/**
 * PostSelector Component
 * 
 * Reusable post selection UI for dynamic array fields.
 * Uses native WordPress components - no external dependencies.
 *
 * @package Handoff_Blocks
 * @generated by Handoff WordPress Compiler
 */

import { useState, useEffect, useMemo } from '@wordpress/element';
import { useSelect } from '@wordpress/data';
import { store as coreDataStore } from '@wordpress/core-data';
import {
  ComboboxControl,
  Spinner,
  Button,
  Card,
  CardBody,
  __experimentalVStack as VStack,
  __experimentalHStack as HStack,
  __experimentalText as Text,
} from '@wordpress/components';
import { __ } from '@wordpress/i18n';
import { closeSmall } from '@wordpress/icons';

/**
 * PostSelector - Select WordPress posts for dynamic array fields
 *
 * @param {Object} props Component props
 * @param {string[]} props.postTypes - Allowed post types
 * @param {Array} props.selectedPosts - Currently selected posts [{id, type}]
 * @param {Function} props.onChange - Callback when selection changes
 * @param {string} props.mode - Selection mode: 'single' or 'multiple'
 * @param {number} props.maxItems - Maximum items for multiple mode
 * @param {string} props.placeholder - Search placeholder text
 */
export function PostSelector({
  postTypes = ['post'],
  selectedPosts = [],
  onChange,
  mode = 'multiple',
  maxItems = 10,
  placeholder = __('Search posts...', 'handoff'),
}) {
  const [searchTerm, setSearchTerm] = useState('');

  // Debounce search term
  const [debouncedSearch, setDebouncedSearch] = useState('');
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(searchTerm);
    }, 300);
    return () => clearTimeout(timer);
  }, [searchTerm]);

  // Fetch posts matching search
  const { searchResults, isLoading } = useSelect(
    (select) => {
      if (!debouncedSearch || debouncedSearch.length < 2) {
        return { searchResults: [], isLoading: false };
      }

      const core = select(coreDataStore);
      const results = [];
      let loading = false;

      for (const postType of postTypes) {
        const query = {
          search: debouncedSearch,
          per_page: 10,
          status: 'publish',
          _fields: 'id,title,type',
        };

        const posts = core.getEntityRecords('postType', postType, query);
        const resolving = core.isResolving('getEntityRecords', [
          'postType',
          postType,
          query,
        ]);

        if (resolving) {
          loading = true;
        }

        if (posts) {
          results.push(
            ...posts.map((p) => ({
              id: p.id,
              type: postType,
              title: p.title?.rendered || p.title || \`Post #\${p.id}\`,
            }))
          );
        }
      }

      // Filter out already selected posts
      const selectedIds = selectedPosts.map((p) => p.id);
      const filtered = results.filter((p) => !selectedIds.includes(p.id));

      return {
        searchResults: filtered.slice(0, 10),
        isLoading: loading,
      };
    },
    [debouncedSearch, postTypes, selectedPosts]
  );

  // Fetch data for selected posts
  const { selectedPostData } = useSelect(
    (select) => {
      const core = select(coreDataStore);
      const data = [];

      for (const selected of selectedPosts) {
        const post = core.getEntityRecord(
          'postType',
          selected.type || 'post',
          selected.id
        );
        if (post) {
          data.push({
            id: post.id,
            type: selected.type || 'post',
            title: post.title?.rendered || post.title || \`Post #\${post.id}\`,
          });
        } else {
          // Show placeholder while loading
          data.push({
            id: selected.id,
            type: selected.type || 'post',
            title: \`Loading... (#\${selected.id})\`,
            loading: true,
          });
        }
      }

      return { selectedPostData: data };
    },
    [selectedPosts]
  );

  // Handle selecting a post from search results
  const handleSelect = (postId) => {
    const post = searchResults.find((p) => String(p.id) === postId);
    if (!post) return;

    if (mode === 'single') {
      onChange([{ id: post.id, type: post.type }]);
    } else {
      if (selectedPosts.length < maxItems) {
        onChange([...selectedPosts, { id: post.id, type: post.type }]);
      }
    }
    setSearchTerm('');
  };

  // Handle removing a selected post
  const handleRemove = (postId) => {
    onChange(selectedPosts.filter((p) => p.id !== postId));
  };

  // Handle reordering (move up/down)
  const handleMoveUp = (index) => {
    if (index === 0) return;
    const newPosts = [...selectedPosts];
    [newPosts[index - 1], newPosts[index]] = [
      newPosts[index],
      newPosts[index - 1],
    ];
    onChange(newPosts);
  };

  const handleMoveDown = (index) => {
    if (index === selectedPosts.length - 1) return;
    const newPosts = [...selectedPosts];
    [newPosts[index], newPosts[index + 1]] = [
      newPosts[index + 1],
      newPosts[index],
    ];
    onChange(newPosts);
  };

  // Build options for ComboboxControl
  const searchOptions = useMemo(() => {
    return searchResults.map((p) => ({
      value: String(p.id),
      label: \`\${p.title} (\${p.type})\`,
    }));
  }, [searchResults]);

  const canAddMore = mode === 'multiple' ? selectedPosts.length < maxItems : selectedPosts.length === 0;

  return (
    <VStack spacing={3} className="handoff-post-selector">
      {/* Search input */}
      {canAddMore && (
        <div className="handoff-post-selector__search">
          <ComboboxControl
            label={placeholder}
            value=""
            onChange={handleSelect}
            onFilterValueChange={(value) => {
              setSearchTerm(value);
            }}
            options={searchOptions}
          />
          {isLoading && (
            <div className="handoff-post-selector__loading">
              <Spinner />
            </div>
          )}
        </div>
      )}

      {/* Selected posts list */}
      {selectedPostData.length > 0 && (
        <VStack spacing={2} className="handoff-post-selector__selected">
          {selectedPostData.map((post, index) => (
            <Card
              key={post.id}
              size="small"
              className="handoff-post-selector__item"
            >
              <CardBody>
                <HStack alignment="center" spacing={2}>
                  {mode === 'multiple' && selectedPosts.length > 1 && (
                    <VStack spacing={0}>
                      <Button
                        icon="arrow-up-alt2"
                        size="small"
                        disabled={index === 0}
                        onClick={() => handleMoveUp(index)}
                        label={__('Move up', 'handoff')}
                      />
                      <Button
                        icon="arrow-down-alt2"
                        size="small"
                        disabled={index === selectedPosts.length - 1}
                        onClick={() => handleMoveDown(index)}
                        label={__('Move down', 'handoff')}
                      />
                    </VStack>
                  )}
                  <div style={{ flex: 1 }}>
                    <Text weight={500}>
                      {post.loading ? (
                        <span style={{ opacity: 0.6 }}>{post.title}</span>
                      ) : (
                        post.title
                      )}
                    </Text>
                    <Text variant="muted" size="small">
                      {post.type}
                    </Text>
                  </div>
                  <Button
                    icon={closeSmall}
                    size="small"
                    isDestructive
                    onClick={() => handleRemove(post.id)}
                    label={__('Remove', 'handoff')}
                  />
                </HStack>
              </CardBody>
            </Card>
          ))}
        </VStack>
      )}

      {/* Empty state */}
      {selectedPosts.length === 0 && (
        <Text variant="muted" align="center">
          {__('No posts selected. Search above to add posts.', 'handoff')}
        </Text>
      )}

      {/* Max items notice */}
      {mode === 'multiple' && selectedPosts.length >= maxItems && (
        <Text variant="muted" align="center">
          {__(\`Maximum of \${maxItems} items reached.\`, 'handoff')}
        </Text>
      )}
    </VStack>
  );
}

export default PostSelector;
`;
};

/**
 * Generate the PostQueryBuilder component code
 */
export const generatePostQueryBuilder = (): string => {
  return `/**
 * PostQueryBuilder Component
 * 
 * A query builder UI for dynamic array fields that lets users:
 * - Select a post type
 * - Add taxonomy filters (categories, tags, custom taxonomies)
 * - Set ordering options
 * - Configure posts per page
 *
 * @package Handoff_Blocks
 * @generated by Handoff WordPress Compiler
 */

import { useState, useEffect } from '@wordpress/element';
import { useSelect } from '@wordpress/data';
import { store as coreDataStore } from '@wordpress/core-data';
import {
  SelectControl,
  TextControl,
  Button,
  Card,
  CardBody,
  CardHeader,
  FormTokenField,
  __experimentalVStack as VStack,
  __experimentalHStack as HStack,
  __experimentalText as Text,
  __experimentalDivider as Divider,
} from '@wordpress/components';
import { __ } from '@wordpress/i18n';
import { closeSmall } from '@wordpress/icons';

/**
 * TaxonomyFilter - Individual taxonomy filter control
 */
function TaxonomyFilter({ taxonomy, selectedTerms, onChange, onRemove }) {
  // Fetch terms for this taxonomy
  const { terms } = useSelect(
    (select) => {
      const core = select(coreDataStore);
      const query = {
        per_page: 100,
        orderby: 'name',
        order: 'asc',
        _fields: 'id,name,slug',
      };

      const fetchedTerms = core.getEntityRecords('taxonomy', taxonomy.slug, query);

      return {
        terms: fetchedTerms || [],
      };
    },
    [taxonomy.slug]
  );

  // Get term names for display
  const termNames = terms.map((t) => t.name);
  const selectedTermNames = selectedTerms
    .map((id) => {
      const term = terms.find((t) => t.id === id);
      return term ? term.name : null;
    })
    .filter(Boolean);

  const handleChange = (newTermNames) => {
    const newTermIds = newTermNames
      .map((name) => {
        const term = terms.find((t) => t.name === name);
        return term ? term.id : null;
      })
      .filter(Boolean);
    onChange(newTermIds);
  };

  return (
    <Card size="small" className="handoff-taxonomy-filter">
      <CardHeader className="handoff-taxonomy-filter__header">
        <HStack alignment="center" style={{ justifyContent: 'space-between', width: '100%' }}>
          <Text weight={500}>{taxonomy.label}</Text>
          <Button
            icon={closeSmall}
            size="small"
            variant="tertiary"
            isDestructive
            onClick={onRemove}
            label={__('Remove filter', 'handoff')}
            style={{ marginLeft: 'auto' }}
          />
        </HStack>
      </CardHeader>
      <CardBody>
        <FormTokenField
          label={__('Select terms', 'handoff')}
          value={selectedTermNames}
          suggestions={termNames}
          onChange={handleChange}
          __experimentalExpandOnFocus
          __experimentalShowHowTo={false}
        />
      </CardBody>
    </Card>
  );
}

/**
 * PostQueryBuilder - Build WordPress queries for dynamic arrays
 */
export function PostQueryBuilder({
  postTypes = ['post'],
  queryArgs = {},
  onChange,
  maxItems = 20,
}) {
  const [availableTaxonomies, setAvailableTaxonomies] = useState([]);

  const currentPostType = queryArgs.post_type || postTypes[0] || 'post';
  const currentPerPage = queryArgs.posts_per_page || 6;
  const currentOrderBy = queryArgs.orderby || 'date';
  const currentOrder = queryArgs.order || 'DESC';
  const currentTaxQueries = queryArgs.tax_query || [];

  // Fetch taxonomies for selected post type
  const { taxonomies } = useSelect(
    (select) => {
      const core = select(coreDataStore);
      const allTaxonomies = core.getTaxonomies({ per_page: -1 });

      if (!allTaxonomies) {
        return { taxonomies: [] };
      }

      const filtered = allTaxonomies.filter(
        (tax) => tax.types && tax.types.includes(currentPostType) && tax.visibility?.show_ui
      );

      return { taxonomies: filtered };
    },
    [currentPostType]
  );

  useEffect(() => {
    if (taxonomies) {
      setAvailableTaxonomies(taxonomies);
    }
  }, [taxonomies]);

  const updateQueryArg = (key, value) => {
    onChange({
      ...queryArgs,
      [key]: value,
    });
  };

  const handlePostTypeChange = (newPostType) => {
    onChange({
      ...queryArgs,
      post_type: newPostType,
      tax_query: [],
    });
  };

  const addTaxonomyFilter = (taxonomySlug) => {
    const newTaxQueries = [
      ...currentTaxQueries,
      {
        taxonomy: taxonomySlug,
        field: 'term_id',
        terms: [],
      },
    ];
    updateQueryArg('tax_query', newTaxQueries);
  };

  const updateTaxonomyFilter = (index, terms) => {
    const newTaxQueries = [...currentTaxQueries];
    newTaxQueries[index] = {
      ...newTaxQueries[index],
      terms,
    };
    updateQueryArg('tax_query', newTaxQueries);
  };

  const removeTaxonomyFilter = (index) => {
    const newTaxQueries = currentTaxQueries.filter((_, i) => i !== index);
    updateQueryArg('tax_query', newTaxQueries);
  };

  const unusedTaxonomies = availableTaxonomies.filter(
    (tax) => !currentTaxQueries.some((tq) => tq.taxonomy === tax.slug)
  );

  const orderByOptions = [
    { label: __('Date', 'handoff'), value: 'date' },
    { label: __('Title', 'handoff'), value: 'title' },
    { label: __('Modified Date', 'handoff'), value: 'modified' },
    { label: __('Menu Order', 'handoff'), value: 'menu_order' },
    { label: __('Random', 'handoff'), value: 'rand' },
    { label: __('Comment Count', 'handoff'), value: 'comment_count' },
  ];

  const orderOptions = [
    { label: __('Descending', 'handoff'), value: 'DESC' },
    { label: __('Ascending', 'handoff'), value: 'ASC' },
  ];

  return (
    <VStack spacing={4} className="handoff-query-builder">
      {/* Post Type Selection */}
      {postTypes.length > 1 && (
        <SelectControl
          label={__('Post Type', 'handoff')}
          value={currentPostType}
          options={postTypes.map((pt) => ({
            label: pt.charAt(0).toUpperCase() + pt.slice(1),
            value: pt,
          }))}
          onChange={handlePostTypeChange}
        />
      )}

      {/* Taxonomy Filters - Moved to top */}
      <div className="handoff-query-builder__filters">
        <Text weight={600} size="12px" style={{ textTransform: 'uppercase', marginBottom: '8px', display: 'block' }}>
          {__('Filters', 'handoff')}
        </Text>

        <VStack spacing={3}>
          {currentTaxQueries.map((taxQuery, index) => {
            const taxonomy = availableTaxonomies.find(
              (t) => t.slug === taxQuery.taxonomy
            );
            if (!taxonomy) return null;

            return (
              <TaxonomyFilter
                key={taxQuery.taxonomy}
                taxonomy={taxonomy}
                selectedTerms={taxQuery.terms || []}
                onChange={(terms) => updateTaxonomyFilter(index, terms)}
                onRemove={() => removeTaxonomyFilter(index)}
              />
            );
          })}

          {unusedTaxonomies.length > 0 && (
            <SelectControl
              label={__('Add Filter', 'handoff')}
              value=""
              options={[
                { label: __('Select taxonomy...', 'handoff'), value: '' },
                ...unusedTaxonomies.map((tax) => ({
                  label: tax.labels?.singular_name || tax.name,
                  value: tax.slug,
                })),
              ]}
              onChange={(value) => {
                if (value) {
                  addTaxonomyFilter(value);
                }
              }}
            />
          )}

          {unusedTaxonomies.length === 0 && currentTaxQueries.length === 0 && (
            <Text variant="muted">
              {__('No taxonomy filters available for this post type.', 'handoff')}
            </Text>
          )}
        </VStack>
      </div>

      <Divider />

      {/* Ordering Options */}
      <HStack alignment="top" spacing={3}>
        <div style={{ flex: 1 }}>
          <SelectControl
            label={__('Order By', 'handoff')}
            value={currentOrderBy}
            options={orderByOptions}
            onChange={(value) => updateQueryArg('orderby', value)}
          />
        </div>
        <div style={{ flex: 1 }}>
          <SelectControl
            label={__('Order', 'handoff')}
            value={currentOrder}
            options={orderOptions}
            onChange={(value) => updateQueryArg('order', value)}
          />
        </div>
      </HStack>

      {/* Posts Per Page - Now a simple number input */}
      <TextControl
        label={__('Posts Per Page', 'handoff')}
        type="number"
        value={String(currentPerPage)}
        onChange={(value) => {
          const num = parseInt(value, 10);
          if (!isNaN(num) && num >= 1 && num <= maxItems) {
            updateQueryArg('posts_per_page', num);
          }
        }}
        min={1}
        max={maxItems}
        help={__(\`Maximum: \${maxItems}\`, 'handoff')}
      />

      {/* Query Preview */}
      <div className="handoff-query-builder__preview" style={{ 
        padding: '12px', 
        backgroundColor: '#f0f0f0', 
        borderRadius: '4px',
        marginTop: '8px'
      }}>
        <Text variant="muted" size="small">
          {__('Showing', 'handoff')} <strong>{currentPerPage}</strong> {currentPostType}
          {currentPerPage !== 1 ? 's' : ''} {__('ordered by', 'handoff')}{' '}
          <strong>{currentOrderBy}</strong> ({currentOrder})
          {currentTaxQueries.length > 0 &&
            \` \${__('with', 'handoff')} \${currentTaxQueries.length} \${
              currentTaxQueries.length === 1 ? __('filter', 'handoff') : __('filters', 'handoff')
            }\`}
        </Text>
      </div>
    </VStack>
  );
}

export default PostQueryBuilder;
`;
};

/**
 * Generate the shared components index file.
 * Exports only DynamicPostSelector (hand-written); PostSelector and PostQueryBuilder
 * are no longer generated and have been replaced by DynamicPostSelector.
 */
export const generateSharedComponentsIndex = (): string => {
  return `/**
 * Shared Components for Handoff Blocks
 * 
 * Dynamic post selection uses DynamicPostSelector (value/onChange/options API).
 *
 * @package Handoff_Blocks
 * @generated by Handoff WordPress Compiler
 */

export { DynamicPostSelector } from './DynamicPostSelector';
`;
};

/**
 * Generate the main shared module index
 */
export const generateSharedIndex = (): string => {
  return `/**
 * Shared utilities and components for Handoff Blocks
 *
 * @package Handoff_Blocks
 * @generated by Handoff WordPress Compiler
 */

export * from './components';
export * from './utils';
`;
};

/**
 * All shared component files that need to be generated.
 * DynamicPostSelector.js is hand-written and not generated; only the index is generated.
 */
export interface SharedComponentFiles {
  'shared/components/index.js': string;
  'shared/index.js': string;
}

/**
 * Generate shared component index files.
 * PostSelector and PostQueryBuilder are no longer generated; use DynamicPostSelector instead.
 */
export const generateSharedComponents = (): SharedComponentFiles => {
  return {
    'shared/components/index.js': generateSharedComponentsIndex(),
    'shared/index.js': generateSharedIndex(),
  };
};
