/**
 * Shared Components for Handoff Blocks
 *
 * Dynamic post selection uses DynamicPostSelector (value/onChange/options API).
 *
 * @package Handoff_Blocks
 * @generated by Handoff WordPress Compiler
 */

export { DynamicPostSelector } from './DynamicPostSelector';
